### PR TITLE
[WIP] Documentation update

### LINKED ISSUE #120: Fix doc
Fix doc on [doc/generator/embed-types.md](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/doc/generator/embed-types.md)

The `collection` type has been replaced with `s2a_collection_table`/`s2a_collection_fieldset` and the `widget` option is no longer valid.

### PR DESCRIPTION
**Pull request by loostro**
This PR is a work in progress. The goal is to completely rewrite all the documentation.

* [x] update README
* [x] bootstrap new documentation structure
* [x] complete Installation section
* [ ] complete Getting started section
* [ ] complete How does this work? section
* [ ] complete Configuration section
* [ ] complete Customization section
* [ ] complete Cookbook section
* [ ] create "Showcase" page with screenshots of demo project on AdminLTE v2 theme
* [ ] remember to fix #120

# Quick draft:

1] Installation

Bundle installation notes.

2] Getting started

Quick guide how to get started.
* assumed knowledge (how to create bundles, models/entities, links to symfony2 doc)
* create admin generator in existing bundle
* create new bundle with admin generator

3] How does this work?

* admingenerator route
* generated "base" controllers and templates
* basic configuration to control built-in features
* extending base files for advanced customization

4] Configuration

* configuration reference for all builders List/Show/New/Edit/Actions/Excel

5] Customization

* how to customize forms/filters/view templates

6] Cookbook

* recipies for common problems, eg. use FormExtensionsBundle, use KnpMenuBundle, non-standard namespace, etc

Fixes: #10, #11, #12, #13, #14, #15, #16, #17, #18, #21.

### CODE REVIEW

**Comment by bobvandevijver** [comment]
:+1: for updating the docs!

**Comment by bobvandevijver** [comment]
Closed in favor of #223.

**Comment by loostro** [comment]
@bobvandevijver can the branch be safely deleted?

**Comment by bobvandevijver** [comment]
Lets keep it for now, I've added it to the to-do list of #223.

**Pull request closed without merging**
