### PR TITLE
Make routing update optional

### LINKED ISSUE #233: Optional routing update when using generate command
In some cases the automatic routing update is not wanted (for example, you want the files in their bundle, and not in the top routing). Before, it was possible to disable that, this is however no longer the case.

### PR DESCRIPTION
**Pull request by sescandell**
FIX #233

/cc @bobvandevijver

### CODE REVIEW

**Comment by bobvandevijver** [comment]
Can't we directly add the functionality to specify the actual location of the routing file, as suggested by @pjam in #233?

**Comment by sescandell** [comment]
Got it, I'll update the PR

**Comment by tobias-93** [comment]
@sescandell I think you left a var_dump in the file in error. Maybe you should remove this?

**Comment by sescandell** [comment]
OOps... many thanks!

**Comment by bobvandevijver** [comment]
Looking good :+1:

**Pull request merged**
