### PR TITLE
Fixes error in path generation and namespace generation when using pr…

### PR DESCRIPTION
**Pull request by tobias-93**
…efixes

### CODE REVIEW

**Comment by sescandell** [comment]
@tobias-93 

Could you please show me how do you "prefix" your generators?

Many thanks,

**Comment by tobias-93** [comment]
@sescandell I use the built-in yaml-prefix functionality of the `GenerateAdminCommand`. For instance, my model is `Idb\EventBundle\Entity\Event` and in our case the generator is placed in `Idb\AdminGeneratorBundle\Resources\config\AdminEvent-generator.yml` (using `AdminEvent` as a prefix). Then, the FormTypes are placed in the `Idb\AdminGeneratorBundle\Form\Type\AdminEvent` namespace. Therefore, the prefix is not equal to an empty string or to the entity-name, but it includes an `Admin` prefix in our case.

**Comment by sescandell** [comment]
... I'm used to use this format too... And everything works but probably because I'm usually using as a prefix my Entity... I'm just wondering so: are you sure about the `$model` concatenation after the prefix?

Don't we have to write: `$formsBundleNamespace = $generatorParameters['namespace_prefix'] . '\\' . $generatorParameters['bundle_name'] . '\\Form\\Type\\' . $generatorParameters['prefix']` (without the `$model` at the end according to the [generation process](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Generator/BundleGenerator.php#L162)

**Comment by tobias-93** [comment]
@sescandell Yeah, my mistake... I'll update in a minute

**Comment by sescandell** [comment]
Many thanks !

**Pull request merged**
