### PR TITLE
Fix route names in AppBundle without vendor

### PR DESCRIPTION
**Pull request by ksn135**
Update RoutingLoader.php

### CODE REVIEW

**Comment by sescandell** [comment]
This PR breaks "everything".

You should also update templates which are still generating routes with underscores at first.
For example:
 - https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/templates/CommonAdmin/ListAction/ListBuilderAction.php.twig#L68
 - https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/templates/CommonAdmin/ListAction/ListBuilderAction.php.twig#L88

There is probably many other part of code like this.

@ksn135 could you please double check that?

Many thanks,

**Comment by ksn135** [comment]
@sescandell sorry, PR is on the way...

**Comment by ksn135** [comment]
Well, 33 matches across 18 files for string ```routePrefixWithSubfolder```
I believe that we need to do some refactoring and replace in templates many code like this ```{{ builder.routePrefixWithSubfolder }}_{{ bundle_name }}{{ builder.BaseGeneratorName ? "_" ~ builder.BaseGeneratorName : "" }}``` to simple function call, i.e. ```{{ builder.baseRoute }}```
@sescandell What do you think about it ?

**Comment by sescandell** [comment]
That will centralize code, which is always a good thing.

Let's do this.

Thanks for your help,

**Comment by ksn135** [comment]
@sescandell add PR #162

**Comment by sescandell** [comment]
Merged.

I'll test it.

THanks,

**Pull request merged**
