### PR TITLE
AdminLTE2 implementation

### LINKED ISSUE #87: [WIP] Update to AdminLTE v2 before V1
Everything is in the title :)

AdminLTE have been released in V2. We need to adapt templates and JS to it before making V1 released.

### PR DESCRIPTION
**Pull request by matejvelikonja**
I've updated bundle to the new version of AdminLTE 2.0. I've did the changes according to [the upgrade guide](https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#upgrade) of the theme.

This is a BC PR, since it uses the new AdminLTE theme and also some twig blocks have been repositioned to fit the new AdminLTE layout.

I've tested it on a simple app I have, so a bit more testing should be done. This PR should fix #87.

### CODE REVIEW

**Comment by sescandell** [comment]
Excellent! Thank you @matejvelikonja 

Any change in templates?

**Comment by matejvelikonja** [comment]
This https://github.com/matejvelikonja/GeneratorBundle/commit/0e465ea82a78fe19153f6544058ea8b56144f105 changed a bit template. Wrapper has been repositioned according to the new layout.

**Comment by sescandell** [comment]
I was more talking about templates files in `https://github.com/symfony2admingenerator/GeneratorBundle/tree/master/Resources/templates`.

I'm going to check it now.

Many thanks for your work

**Comment by sescandell** [comment]
Hi @matejvelikonja 

I linked your PR to the demo project, and some things are not fully ready for adminlte2.

This is what I've seen:
 - Error flash:
capture d ecran 2015-03-28 a 14 30 56


And actually, that's all!

Could you please fix this, and we should be able to merge it.

Many thanks!!

**Comment by loostro** [comment]
I'm looking forward to test this. Will probably do that on monday.

**Comment by matejvelikonja** [comment]
Actually this was a problem from before. There was a typo `dange` -> `danger`. This commit should fix this.

**Comment by sescandell** [comment]
Sounds good for me.

@loostro I've tested it, for me, we can merge it now!

**Comment by loostro** [comment]
OK. THanks :)

**Pull request merged**
