### PR TITLE
Non standard dbtypes

### PR DESCRIPTION
**Pull request by loostro**

### CODE REVIEW

**Comment by loostro** [comment]
TODO: add validate method which should load the default options if they are not present

**Comment by loostro** [comment]
@sescandell Please review. The PR solves the problem of non standard fieldtypes and also adds a nice feature: you only have to define the field types you want to overwrite. 

Previous to this patch, if you wanted to change one field type, eg. `boolean => choice`, you had to copy/paste all the default types. Now you can simply do:

```
admingenerator_generator:
    formTypes:
        doctrine_orm:
            boolean: checkbox
    # no need to copy the default values for other field types
```

**Comment by bobvandevijver** [comment]
@loostro @sescandell Exactly want I wanted to achieve :+1:

**Comment by sescandell** [comment]
OK for me, nice one !

**Comment by loostro** [comment]
@tobias-93 thanks for help :) merged

**Comment by tobias-93** [comment]
@loostro cool, you're welcome!

**Pull request merged**
