### PR TITLE
Add a Propel date range filter & force Propel boot init

### PR DESCRIPTION
**Pull request by Lionel09**
cf https://github.com/symfony2admingenerator/FormExtensionsBundle/issues/52

It has to be improved:
- only for Propel
- need to make a function inheritage in the ListController to work

cf https://github.com/symfony2admingenerator/GeneratorBundle/issues/217

Check if Propel is used and force Propel::init before warmup

Note: sorry because I've failed to do 2 differents PR for this 2 issues

### CODE REVIEW

**Comment by sescandell** [comment]
Hi @Lionel09 

Thanks for your activities these days, we really appreciate it!

Speaking about the `addDateRangeFilter` I'm just not convinced about that modification. I think you should change the `addDateFilter` rather than creating a new one that is not referenced anywhere (meaning that except by overriding the controller, this function is never used). As far as I understand your update could be moved to the `addDateFilter`.

Does it make sense for your?

**Comment by Lionel09** [comment]
yes it does, i'll update asap

**Comment by sescandell** [comment]
Thanks, merged!

**Comment by Lionel09** [comment]
Can you put theses PR updates in the Packagist repo too, to be able to make a "composer require"?

Sorry but I don't know exactly what is the process in this case.

**Comment by sescandell** [comment]
Done: https://github.com/symfony2admingenerator/GeneratorBundle/releases/tag/v2.0-beta42

Just wait for some minutes so packagist is up to date

**Pull request merged**
