### PR TITLE
Update breadcrumbs.md

### PR DESCRIPTION
**Pull request by ksn135**
remove Russian letters

### CODE REVIEW

**Comment by bobvandevijver** [comment]
Nice, thanks! You also added some code? Is that correct?

Do you see any chance to also update the image?

**Comment by ksn135** [comment]
2016-03-02 12-25-05 banners and alerts

**Comment by ksn135** [comment]
@bobvandevijver I don't know how to upload it (see previous comment) ... (

**Comment by bobvandevijver** [comment]
Ok, will fix, thanks :+1:

**Pull request merged**
