### PR TITLE
Fixed #288, auto generated form types now have unique service name, no possibility for overwritting.

### LINKED ISSUE #288: Possible bug in Admingenerator\GeneratorBundle\DependencyInjection\AdmingeneratorGeneratorExtension::registerFormsServicesFromGenerator
Every auto-generated form is registered in: `Admingenerator\GeneratorBundle\DependencyInjection\AdmingeneratorGeneratorExtension::registerFormsServicesFromGenerator` 

Pattern is: 

` $container->setDefinition('admingen_generator_' . strtolower($model) . '_edit', $editDefinition);`

Note that `_edit` can be `_new` and `_filter` as well.

` strtolower($model)` is used, and model is class name **without** namespace prefix.

That means that, per example, classes:

- `\One\ModelX`
- `\Two\ModelX`

Would have generated form type service under the same name:

- `admingen_generator_modelx_edit`, and so on...

That means that in case when we have models with same name under different namespaces, form type services gets overridden. 

This is easy fix, can someone confirm this, just another pair of eyes, in case I am missing something?

### PR DESCRIPTION
**Pull request by loostro**
Squashed #290

### CODE REVIEW

**Comment by loostro** [comment]
@sescandell Was the service definition feature documented anywhere? I couldnt find it. If it was, we should also update the docs.

**Comment by TheCelavi** [comment]
@loostro This one is missing code, not correct PR. Oh man, I made a mess... #290 has proper code in it.

**Comment by loostro** [comment]
@TheCelavi I copied the missing upgrade notes. I don't see anything else missing from your PR.

**Comment by TheCelavi** [comment]
@loostro 

Line 273:

    $fullQualifiedNormalizedModelName = strtolower(str_replace('\\', '_', ltrim($generatorParameters['model'])));

Function `ltrim` is missing second parameter which should be double backslash (\\)

    $fullQualifiedNormalizedModelName = strtolower(str_replace('\\', '_', ltrim($generatorParameters['model'], '\\')));

**Comment by sescandell** [comment]
> @sescandell Was the service definition feature documented anywhere? I couldnt find it. If it was, we should also update the docs.

Do you mean explanation on how all of this is working? or "generated names"?

**Comment by TheCelavi** [comment]
@loostro In #292 I have fixed the mess which I caused yesterday, sorry. I have just committed a cookbook entry as well in regards dependency injection for form types.

@sescandell In cookbook entry I have tried to explain in details how service names are generated for form types, so take a look at [https://github.com/RunOpenCode/GeneratorBundle/blob/82d0cec04bc723d26093097d66ba1070fac00875/Resources/doc/cookbook/inject-services-into-form-types.md](https://github.com/RunOpenCode/GeneratorBundle/blob/82d0cec04bc723d26093097d66ba1070fac00875/Resources/doc/cookbook/inject-services-into-form-types.md) and see if this is documented good enough.

**Comment by loostro** [comment]
Closed in favor of #292

**Pull request closed without merging**
