### PR TITLE
Fix build for a propel app 

### PR DESCRIPTION
**Pull request by cedriclombardot**
Fix build for a propel app :

- Add missing FiltersBuilderTemplate.php.twig
- Fix Guesser/PropelORMFieldGuesser.php
- Ensure ArrayExtension loaded in base builder

### CODE REVIEW

**Comment by loostro** [comment]
@neoshadybeat @sescandell @cedriclombardot Any idea why Scrutinizer always fails on 41%?

It's not just this PR's. It was the same with my documenatation PR.

scr

**Comment by sescandell** [comment]
I have no idea what this task represents in Scrutinizer...

**Comment by sescandell** [comment]
Otherwise, regarding the PR, sounds good for me,

**Comment by loostro** [comment]
The scrutinizer error is unrelated. I've created a seperate issue for it. Merging. Thanks.

**Pull request merged**
