### PR TITLE
Update paginator.php.twig

### PR DESCRIPTION
**Pull request by calvera**
I think it is better to use dropup instead of dropdown. In case list is at bottom it displays list correctly...

### CODE REVIEW

**Comment by sescandell** [comment]
Hi @calvera 

Thanks for your contribution.

Could you please attach a screenshot of this PR?

Thanks!

**Comment by calvera** [comment]
Here it is...

display_n_elements_popup

**Comment by bobvandevijver** [comment]
I agree with this! :+1:

**Comment by sescandell** [comment]
Merged,

Thanks,

**Pull request merged**
