### PR TITLE
Fix sensio insight issues

### PR DESCRIPTION
**Pull request by loostro**
Fix major sensio insight issues:

* `__DIR__` and `__FILE__` constants may conflict with the Symfony resource overriding system
* Files should not be executable

### CODE REVIEW

**Comment by loostro** [comment]
Please review.

**Comment by sescandell** [comment]
Hi @loostro 

I don't understand why `__DIR__` and `__FILE__` are not a good thing?

**Comment by loostro** [comment]
@sescandell it's a change suggested by SensioLabs Insight, I'd like to fix all scrutinizer/insight issues and improve tests code coverage and then make a symfony installer for `symfony2-admingenerator-edition` to promote our bundle

[see senso insight analysis](https://insight.sensiolabs.com/projects/e8ee4e4c-d8fb-4354-96c3-8971dce11201/analyses/4)

**Comment by loostro** [comment]
@sescandell Are you OK to merge this? I'm trying to improve code quality by fixing scrutinizer/sensio issues/notices, but if there is any reason this is wrong and should not be merged, please let me know.

**Comment by loostro** [comment]
Discussion on gitter concluded with recommendation to use resource locator instead of ReflectionClass:

```php
$kernel = $container->getService('kernel');
$path = $kernel->locateResource('@AdmeDemoBundle/path/to/file/Foo.txt');
```

@TODO consider this option and possibly update the PR

**Comment by sescandell** [comment]
Maybe another alternative would be to use Puli: https://github.com/puli

**Comment by loostro** [comment]
I'll make a test project and check out all the possibilities today.

**Comment by loostro** [comment]
Moved fix file permissions to another PR and closeing this one. I'll test diffrent solutions and propose another PR soon.

**Comment by loostro** [comment]
TODO: not enough time today. I'll be back on this tomorrow.

**Pull request closed without merging**
